### ISSUE TITLE
What is the file to reference in eyamlPath?

### ISSUE THREAD

**Issue by simonmackinnon** [brandontosch/vscode-hiera-eyaml#5]
I've installed the hiera-eyaml gem, and set up my keys using the setup at https://github.com/voxpupuli/hiera-eyaml

I can get the cli for this working, e.g.:
![image](https://user-images.githubusercontent.com/4686123/38710140-24ddbaf4-3f02-11e8-9c4a-b726dfa56262.png)

I've installed the VS Code Hiera-Eyaml extension, and have set up the following user settings:

"hiera-eyaml": {
        "eyamlPath": "C:\\Ruby24-x64\\lib\\ruby\\gems\\2.4.0\\gems\\hiera-eyaml-2.1.0\\lib\\hiera\\backend\\eyaml.rb",
        "publicKeyPath": "C:\\Workspace\\keys\\public_key.pkcs7.pem",
        "privateKeyPath": "C:\\Workspace\\keys\\private_key.pkcs7.pem",
        "outputFormat": "String"
    }

When I attempt to encrypt/decrypt a string, it removes the string, but throws no error. I've tried with the 
"C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\hiera-eyaml-2.1.0\lib\hiera\backend\eyaml_backend.rb" path as well as "C:\Ruby24-x64\lib\ruby\gems\2.4.0\gems\hiera-eyaml-2.1.0\lib\hiera\backend\eyaml\CLI.rb" (the latter of which throws some require errors).

What is the correct file to point to for this to work?

**Comment by gettingstuffdone** [comment]
@simonmackinnon if you type 'which eyaml' in the cmd prompt it will point you to the correct path
for me this is: C:/Ruby25-x64/bin/eyaml
note: that the slashes should be forward slashes as above so vscode doesn't regard them as escapes

**Comment by simonmackinnon** [comment]
Yes, that worked!Thanks! 

I got the following:

>where eyaml
C:\Ruby24-x64\bin\eyaml
C:\Ruby24-x64\bin\eyaml.bat

and set the following settings in the VS.Code User Settings file:

>{
    "hiera-eyaml": {
        "eyamlPath": "C:\\Ruby24-x64\\bin\\eyaml",
        "publicKeyPath": "C:\\path\\to\\keys\\public_key.pkcs7.pem",
        "privateKeyPath": "C:\\path\\to\\keys\\private_key.pkcs7.pem",
    }
}

And now I can encrypt/decrypt using the plugin
